### ISSUE TITLE
Bower registry entry should be fine-uploader, not fineuploader-dist

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/bower-dist#9]
We will likely need to get Bower staff involved to make this happen. I noticed there is a fineuploader-dist entry and a fine-uploader entry. The fineuploader-dist entry seems 3rd-party and unofficial. It really should be fine-uploader. The fine-uploader entry is likely very old and completely wrong.

**Comment by rnicholus** [comment]
One this is completed, I can list bower as an option in the getting started guide (and elsewhere).

**Comment by feryardiant** [comment]
The only thing we can do to solve this issue is remove current *fine-uploader* from bower registry and rename this distribution to correct name. Let me know what you thing @rnicholus

**Comment by rnicholus** [comment]
@feryardiant That sounds good to me.

**Comment by feryardiant** [comment]
Shall we do it now?

**Comment by rnicholus** [comment]
Fine with me. The current fine-uploader registry entry is either very old and/or contains invalid artifacts.

**Comment by feryardiant** [comment]
Great, I'll waiting fine-uploader to be deleted first.

**Comment by rnicholus** [comment]
I think you can simply request that by contacting the bower people

**Comment by feryardiant** [comment]
No need to contact anyone. We can simply execute `bower unregister fine-uploader` 😉 

![image](https://cloud.githubusercontent.com/assets/508665/18599183/3bd80c54-7c81-11e6-8afd-e0283844b0af.png)

But, I think I'm not autorized as package owner or something. The command said it unregistered but I try to find on bower website or libraries.io it still there. Could you confirm that?

**Comment by rnicholus** [comment]
Looks good to me:

```bash
[rnicholus-macbookpro:temp rnicholus$ node_modules/bower/bin/bower install fine-uploader
bower ENOTFOUND     Package fine-uploader not found
```

**Comment by feryardiant** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/508665/18600766/86010440-7c89-11e6-8d7b-7f0a71beaf6c.png)

**Comment by rnicholus** [comment]
Looks like `bower install fine-uploader` creates a `fineuploader-dist` directory in bower_components.

**Comment by feryardiant** [comment]
Yes, because our [latest release](https://github.com/FineUploader/bower-dist/releases) is 5.11.0 and the `bower.json` file still *fineuploader-dist*, that should be fixed sortly.

**Comment by rnicholus** [comment]
👍 . I'll close this then. Thanks!

**Comment by sojimon** [comment]
I removed fineuploader-dist from the bower.json and I install fine-uploader by `bower install fine- uploader ` .On ember server, I get the following error in terminal.

`The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/var/www/newProject/front-end/tmp/source_map_concat-input_base_path-wX1K2MH1.tmp/0/bower_components/fineuploader-dist/dist/s3.jquery.fine-uploader.min.js'
    at Object.fs.statSync (fs.js:907:18)
    at Concat.keyForFile (/var/www/newProject/front-end/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at Concat.CachingWriter._conditionalBuild (/var/www/newProject/front-end/node_modules/broccoli-caching-writer/index.js:109:65)
    at /var/www/newProject/front-end/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at tryCatch (/var/www/newProject/front-end/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/var/www/newProject/front-end/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/var/www/newProject/front-end/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/var/www/newProject/front-end/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at Concat.Plugin (/var/www/newProject/front-end/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at Concat.CachingWriter [as constructor] (/var/www/newProject/front-end/node_modules/broccoli-caching-writer/index.js:18:10)
    at new Concat (/var/www/newProject/front-end/node_modules/broccoli-concat/concat.js:32:17)
    at module.exports (/var/www/newProject/front-end/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/var/www/newProject/front-end/node_modules/ember-cli/lib/broccoli/ember-app.js:346:10)
    at EmberApp.javascript (/var/www/newProject/front-end/node_modules/ember-cli/lib/broccoli/ember-app.js:1212:12)
    at EmberApp.toArray (/var/www/newProject/front-end/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:10)
    at EmberApp.toTree (/var/www/newProject/front-end/node_modules/ember-cli/lib/broccoli/ember-app.js:1586:30)
    at module.exports (/var/www/newProject/front-end/ember-cli-build.js:132:14)
    at Class.setupBroccoliBuilder (/var/www/newProject/front-end/node_modules/ember-cli/lib/models/builder.js:55:19)
`

**Comment by sojimon** [comment]
I removed fineuploader-dist from the bower.json and I install fine-uploader by bower install fine- uploader .On ember server, I get the following error in terminal.

`The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/var/www/newProject/front-end/tmp/source_map_concat-input_base_path-wX1K2MH1.tmp/0/bower_components/fineuploader-dist/dist/s3.jquery.fine-uploader.min.js'
at Object.fs.statSync (fs.js:907:18)
at Concat.keyForFile (/var/www/newProject/front-end/node_modules/broccoli-caching-writer/index.js:87:20)
at Array.map (native)
at Concat.CachingWriter._conditionalBuild (/var/www/newProject/front-end/node_modules/broccoli-caching-writer/index.js:109:65)
at /var/www/newProject/front-end/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
at tryCatch (/var/www/newProject/front-end/node_modules/rsvp/dist/rsvp.js:539:12)
at invokeCallback (/var/www/newProject/front-end/node_modules/rsvp/dist/rsvp.js:554:13)
at publish (/var/www/newProject/front-end/node_modules/rsvp/dist/rsvp.js:522:7)
at flush (/var/www/newProject/front-end/node_modules/rsvp/dist/rsvp.js:2414:5)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
at Concat.Plugin (/var/www/newProject/front-end/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
at Concat.CachingWriter [as constructor] (/var/www/newProject/front-end/node_modules/broccoli-caching-writer/index.js:18:10)
at new Concat (/var/www/newProject/front-end/node_modules/broccoli-concat/concat.js:32:17)
at module.exports (/var/www/newProject/front-end/node_modules/broccoli-concat/index.js:26:10)
at EmberApp.concatFiles (/var/www/newProject/front-end/node_modules/ember-cli/lib/broccoli/ember-app.js:346:10)
at EmberApp.javascript (/var/www/newProject/front-end/node_modules/ember-cli/lib/broccoli/ember-app.js:1212:12)
at EmberApp.toArray (/var/www/newProject/front-end/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:10)
at EmberApp.toTree (/var/www/newProject/front-end/node_modules/ember-cli/lib/broccoli/ember-app.js:1586:30)
at module.exports (/var/www/newProject/front-end/ember-cli-build.js:132:14)
at Class.setupBroccoliBuilder (/var/www/newProject/front-end/node_modules/ember-cli/lib/models/builder.js:55:19)
And I can founds3.jquery.fine-uploader.min.json the location '/var/www/newProject/front-end/tmp/source_map_concat-input_base_path-wX1K2MH1.tmp/0/bower_components/fine-uploadert/dist' instead of 'var/www/newProject/front-end/tmp/source_map_concat-input_base_path-wX1K2MH1.tmp/0/bower_components/fineuploader-dist/dist/ '
